# Generated by Django 3.2.3 on 2021-05-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.IntegerField(blank=True, default=25, null=True)),
                ('humid', models.IntegerField(blank=True, null=True)),
                ('distance_door', models.IntegerField(blank=True, null=True)),
                ('distance_private_room', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('auto', models.BooleanField(blank=True, default=True, null=True)),
                ('pin_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_home.house')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.type')),
            ],
        ),
    ]
