# Generated by Django 3.2.4 on 2021-06-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0002_auto_20210530_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10, null=True, verbose_name='Status')),
                ('auto', models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10, null=True, verbose_name='Auto')),
                ('pin_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_home.home')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_home.type')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.DeleteModel(
            name='Devide',
        ),
    ]
