# Generated by Django 3.2.5 on 2021-07-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0004_auto_20210706_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
