# Generated by Django 3.2.5 on 2021-07-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='esp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_device', to='smart_home.esp'),
        ),
        migrations.AlterField(
            model_name='home',
            name='distance_door',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='distance_private_room',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='humid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='temperature',
            field=models.FloatField(blank=True, default=25, null=True),
        ),
    ]
