# Generated by Django 3.2.5 on 2021-07-20 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0007_remove_device_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_esp', to='smart_home.home'),
        ),
    ]
